name: Coding repos mirror periodic job

on:
  push:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache projectceladon src repos
      uses: actions/cache@v1
      with:
        path: /home/runner/work/jingdlu_coding_mirror/jingdlu_coding_mirror/jingdlu_coding_mirror-cache
        key: ${{ runner.os }}-jingdlu_coding_mirror-repos-cache

    - name: Mirror the Github organization repos to Coding.
      uses: jingdlu/hub-mirror-action@master
      with:
        src: github/projectceladon
        dst: coding/projectceladon
        dst_key: ${{ secrets.CODING_PRIVATE_KEY }}
        dst_token:  ${{ secrets.CODING_TOKEN }}
        force_update: true
        account_type: org
        black_list: "celadon-binary,linux-intel-lts2019-chromium,linux-intel-lts2019-yocto,linux-intel-lts,device-androidia-kernel,mainline-tracking"
        cache_path: /github/workspace/jingdlu_coding_mirror-cache
