name: Coding repos mirror periodic job

on:
  push:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache kunpengcompute src repos
      uses: actions/cache@v1
      with:
        path: /home/runner/work/jingdlu_log_capture/jingdlu_log_capture/jingdlu_log_capture-cache
        key: ${{ runner.os }}-jingdlu_log_capture-repos-cache

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.05
      with:
        src: github/jingdlu
        dst: gitee/projectceladon
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        cache_path: /github/workspace/jingdlu_log_capture-cache
